### ISSUE TITLE
Question: is there a plan to migrate to ISO GQL

### ISSUE THREAD

**Issue by haoxins** [drasi-project/drasi-core#33]
### Overview of feature request

Hi,
The IOS GQL was published this year and evolved from the Cypher query language.
So I want to ask whether this project will switch to IOS GQL as the mainstream graph databases have already announced the adoption and support plan.

### Would you like to support us?

- [X] Yes, I would like to support you

**Comment by agentofreality** [comment]
One of the reasons we initially chose Cypher as the Drasi query langugae was because of the influence Cypher was having on the GQL standard and we felt we would be closer to GQL once it was released. So it is definitely a direction we have been anticipating, but we have no timeframe as to when we will look into this. Currently we are prioritizing making Drasi easier to use/adopt and working with community members to understand if/how/where Drasi can add value for them. If you/somebody wanted to look into how Drasi would support GQL, we would love to talk to you.

**Comment by haoxins** [comment]
Thanks for the explanation. I'm optimistic about this project, but I don't have much free time to invest at this moment.
I will close this issue first as the question has been answered, but cc @wey-gu maybe he is interested.
